<?php


namespace Vxsoft\Setup\Acedamic\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vxsoft\Main\Constant\Constant;
use Vxsoft\Setup\Acedamic\Entity\Affiliation;
use Vxsoft\Setup\Acedamic\Entity\Faculty;
use Vxsoft\Setup\Acedamic\Entity\Level;
use Vxsoft\Setup\Acedamic\Entity\ProgramSystem;

class ProgramSystemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', TextType::class,[])
            ->add('abbreviation',TextType::class,[])
            ->add('duration')
            ->add('durationType',ChoiceType::class,[
                'placeholder'=> '-- Select Duration Type --',
                'choices'=> array_flip(Constant::$durationTypes)
            ])
            ->add('numberOfSession')
            ->add('description')
            ->add('programType', ChoiceType::class,[
                'placeholder'=> '-- Select Program Type --',
                'choices' => array_flip(ProgramSystem::$programSystemType)
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        return $resolver->setDefaults([
            'data_class' => ProgramSystem::class
        ]);
    }

    public function getBlockPrefix()
    {
        return 'level_type'; // TODO: Change the autogenerated stub
    }


}