<?php


namespace Vxsoft\Course\Form;


use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vxsoft\Course\Entity\Course;
use Vxsoft\Course\Entity\ElectiveCourse;
use Vxsoft\Course\Repository\CourseRepository;

class ElectiveCourseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name')
            ->add('code')
            ->add('course', EntityType::class, [
                'class'=> Course::class,
                'required'=> true,
                'placeholder'=> '-- Select Course ---',
                'query_builder' => function(CourseRepository $repository){
                return $repository->createQueryBuilder('c')
                    ->where('c.deleted = 0')
                    ->andWhere('c.type =:type')
                    ->setParameter('type', Course::COURSE_TYPE_ELECTIVE);
                }

            ])
            ->add('overview', TextareaType::class,[
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ElectiveCourse::class
        ]);
    }

    public function getBlockPrefix()
    {
        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }


}