<?php


namespace Vxsoft\Exam\Form;


use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vxsoft\Batch\Entity\Batch;
use Vxsoft\Batch\Entity\BatchSession;
use Vxsoft\Batch\Repository\BatchRepository;
use Vxsoft\Batch\Repository\BatchSessionRepository;
use Vxsoft\Exam\Entity\Exam;
use Vxsoft\Program\Entity\Program;
use Vxsoft\Program\Repository\ProgramRepository;
use Vxsoft\Setup\Acedamic\Entity\Faculty;
use Vxsoft\Setup\Acedamic\Repository\FacultyRepository;

class ExamType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name',TextType::class,[
            'required' => true,
        ] )
            ->add('examYear', DateTimeType::class,[
                'required' => true,
            ])

            ->add('program', EntityType::class, [
                'required'=> false,
                'class'=> Program::class,
                'placeholder'=> '-- Select Program --',
                'query_builder' => function (ProgramRepository $repo){
                    return $repo->createQueryBuilder('f')
                        ->where('f.deleted = 0');
                },
                'attr' => [
                    'class' => 'hide-form'
                ]
            ] )
            ->add('batch', EntityType::class,[
                'required'=> false,
                'class'=> Batch::class,
                'placeholder'=> '-- Select Batch --',
                'query_builder' => function (BatchRepository $repo){
                    return $repo->createQueryBuilder('f')
                        ->where('f.deleted = 0');
                },
                'attr' => [
                    'class' => 'hide-form'
                ]
            ])
            ->add('batchSession', EntityType::class,[
                'required'=> false,
                'class'=> BatchSession::class,
                'placeholder'=> '-- Select Batch Session --',
                'query_builder' => function (BatchSessionRepository $repo){
                    return $repo->createQueryBuilder('f')
                        ->where('f.deleted = 0');
                },
                'attr' => [
                    'class' => 'hide-form'
                ]
            ])
            ->add('description',TextareaType::class,[
                'required' => true,
                'attr' => [
                    'class' => 'description'
                ]
            ] )
            ->add('nonAcademic', RadioType::class,[]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
       return $resolver->setDefaults([
           'data_class' => Exam::class,
       ]);
    }

    public function getBlockPrefix()
    {
        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }


}